 data = [{
    "index": 0,
    "Name": "VINSON,BRAXTON MCCRAY",
    "Age": 16,
    "Sex": "F",
    "Residence": "569 S LITTLE TEXAS KANNAPOLIS, NC 28083",
    "Employer": "NONE",
    "arrest_date": "04-06-2015",
    "arrest_location": "3301 HAMMOND RD. RALEIGH, NC",
    "ArrestingOfficer": "WR SANDERS-RPD",
    "agency": "RALEIGH",
    "Charge": "FAIL REPRT NEW ADDRESS-SEX OFF (CABARRUS CO)"
},
{
    "index": 1,
    "Name": "LORFILS,GILBERT TRAVIS",
    "Age": 16,
    "Sex": "M",
    "Residence": "ANYWHERE ANYWHERE, NC 27529",
    "Employer": "NONE",
    "arrest_date": "05-31-2015",
    "arrest_location": "2507 NOBLIN RD RALEIGH, NC",
    "ArrestingOfficer": "RM CARROLL-RPD",
    "agency": "RALEIGH",
    "Charge": "FELONY POSSESSION OF COCAINE"
},
 {
    "index": 2,
    "Name": "LORFILS,GILBERT TRAVIS",
    "Age": 32,
    "Sex": "M",
    "Residence": "ANYWHERE ANYWHERE, NC 27529",
    "Employer": "NONE",
    "arrest_date": "05-31-2015",
    "arrest_location": "2507 NOBLIN RD RALEIGH, NC",
    "ArrestingOfficer": "RM CARROLL-RPD",
    "agency": "Cary",
    "Charge": "RESISTING PUBLIC OFFICER",
 },
 {
    "index": 3,
    "Name": "VINSON,BRAXTON MCCRAY",
    "Age": 27,
    "Sex": "F",
    "Residence": "569 S LITTLE TEXAS KANNAPOLIS, NC 28083",
    "Employer": "NONE",
    "arrest_date": "04-06-2015",
    "arrest_location": "3301 HAMMOND RD. RALEIGH, NC",
    "ArrestingOfficer": "WR SANDERS-RPD",
    "agency": "RALEIGH",
    "Charge": "FAIL REPRT NEW ADDRESS-SEX OFF (CABARRUS CO)"
},
{
    "index": 4,
    "Name": "LORFILS,GILBERT TRAVIS",
    "Age": 32,
    "Sex": "M",
    "Residence": "ANYWHERE ANYWHERE, NC 27529",
    "Employer": "NONE",
    "arrest_date": "05-31-2015",
    "arrest_location": "2507 NOBLIN RD RALEIGH, NC",
    "ArrestingOfficer": "RM CARROLL-RPD",
    "agency": "RALEIGH",
    "Charge": "FELONY POSSESSION OF COCAINE"
},
 {
    "index": 5,
    "Name": "LORFILS,GILBERT TRAVIS",
    "Age": 32,
    "Sex": "M",
    "Residence": "ANYWHERE ANYWHERE, NC 27529",
    "Employer": "NONE",
    "arrest_date": "05-31-2015",
    "arrest_location": "2507 NOBLIN RD RALEIGH, NC",
    "ArrestingOfficer": "RM CARROLL-RPD",
    "agency": "Cary",
    "Charge": "RESISTING PUBLIC OFFICER"
}]